### ISSUE TITLE
User Registration Implementation

### ISSUE THREAD

**Issue by indrazm** [indrazm/eventmakers#2]
Create user registration functionality, including sign-up form, user database, and authentication.

### Task

- [ ] Design user registration form.
- [ ] Set up user database.
- [ ] Implement user authentication.
